name: first deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deploying ..." 
